### ISSUE TITLE
Support directories in the scaffold base

### ISSUE THREAD

**Issue by gregorskii** [chenasraf/simple-scaffold#1]
Hi,

Seems like this does not support folders inside of the scaffolding directory.

I get:

```
EISDIR: illegal operation on a directory, read
```

Due to https://github.com/chenasraf/simple-scaffold/blob/master/scaffold.ts#L89

**Comment by chenasraf** [comment]
Hi, sorry for the LONG delay - can you elaborate what you mean to help me reproduce?
