### ISSUE TITLE
[BUG] On Windows, tries to write to temp dir instead of output dir and fails

### ISSUE THREAD

**Issue by o68x** [chenasraf/simple-scaffold#107]
#### Describe the bug

On Windows, simple-scaffold writes the output to temp dir instead of output dir

#### How To Reproduce

Use github config file

   ```shell
   npx simple-scaffold -g o68x/my-simple-scaffolds -c scaffold.js -k duplicacy name -l debug
   ```

#### Expected behavior\*\*

Should write to the output dir (here the working dir)

#### Logs

[log.txt](https://github.com/user-attachments/files/17154510/log.txt)

#### Desktop

- OS:Windows
- OS Version: 10
- Node.js: 20.17.0
- Simple Scaffold Version 2.3.0

**Comment by chenasraf** [comment]
Thanks for the report, seems pretty clear how to fix this, I'll try to push a fix within the next few days. Sorry for the inconvenience!

**Comment by chenasraf** [comment]
Just letting you know I haven't forgotten - I'm just having some trouble getting hold of a Windows computer to test on

If you wanna try build the PR version yourself and give it a go, be my guest

If not it might take another day or two, apologize in advance

**Comment by o68x** [comment]
I will try that tomorrow! Thanks a lot!

**Comment by chenasraf** [comment]
Cool, if there are issues post another log and I would be happy to continue to work on it

If it works I will merge it to master soon

**Comment by o68x** [comment]
Thanks for the PR! It strips the tmpDir alright, but then writes to the root instead of the working dir.

```
Full input path: C:\Users\Olivier\AppData\Local\Temp\scaffold-config-1727758941877-98824307lcw\duplicacy\duplicacy.mjs
Output Path Opt: C:\Users\Olivier\code\test
Full output dir: C:\duplicacy
Full output path: C:\duplicacy\duplicacy.mjs
```

Thanks again for your work!

[log-fix-output-dir.txt](https://github.com/user-attachments/files/17199604/log-fix-output-dir.txt)

**Comment by chenasraf** [comment]
Got it, will push an update later today

**Comment by chenasraf** [comment]
Sorry for the delay - if you can try it out now and let me know if it works that would be great :)

Thanks for your patience :)

**Comment by o68x** [comment]
It's all good now! Thank you :)
