### ISSUE TITLE
Deprecation warning when including from Node

### ISSUE THREAD

**Issue by jonnysamps** [chenasraf/simple-scaffold#14]
Hey there, thanks for providing this package. I'm just getting going trying to use it but the first time I did I get this warning when running the app:

```
(node:3555) [DEP0128] DeprecationWarning: Invalid 'main' field in '/app/node_modules/simple-scaffold/package.json' of 'dist/scaffold.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
```

Using:
node v16.0.0

Here is the code that's using it:

```typescript
import SimpleScaffold from 'simple-scaffold';

async function main  {
      const scaffold = new SimpleScaffold({
        name: projectName,
        templates: [join(__dirname, "commands", "new", "templates")],
        output: process.cwd(),
        createSubfolder: true,
        locals: {
          description: 'something or other'
        }
      }).run();
}
main();
```

Found that I can suppress the warnings by adding this at the top of my app but its not ideal:

```
process.removeAllListeners('warning');
```

**Comment by chenasraf** [comment]
Hi @jonnysamps, sorry it took so long to see this. I will upload a new release shortly that removes this field from `package.json`. Luckily this is a quick fix.

**Comment by chenasraf** [comment]
[Release v0.7.5](https://github.com/chenasraf/simple-scaffold/releases/tag/v0.7.5) should fix this issue, please let me know if it it still occuring.

**Comment by jonnysamps** [comment]
looking good! Thanks!
