### ISSUE TITLE
Not respecting subfolder file placement

### ISSUE THREAD

**Issue by shaneajeffery** [chenasraf/simple-scaffold#18]
Hey there!

The tool works great for my use case minus one glaring issue.  When I run my command `./node_modules/.bin/simple-scaffold text-field -t scaffolds/new-package/**/* -o packages`, all of the contents get created properly but the files that were in the subdirectories just get put in the root of the directory.

Also, MDX files don't seem to work for the handlebars variable replacements.

Thanks for any help you can provide!

<img width="409" alt="Screen Shot 2021-10-02 at 12 32 17 PM" src="https://user-images.githubusercontent.com/69131241/135729703-eb345c38-fa95-40a9-9ff9-d0b8fc5a65f5.png">

<img width="402" alt="Screen Shot 2021-10-02 at 12 32 24 PM" src="https://user-images.githubusercontent.com/69131241/135729706-a8512cc3-126f-487f-a993-23a5cd5b9796.png">

**Comment by chenasraf** [comment]
Hi @shaneajeffery, sorry for the delayed response.

This is odd behavior, I'm pretty sure it should maintain folder structure. 

I will look into why this might happen.

While I am investigating, can I ask, are you using a terminal like `zsh` or `fsh` that automatically expand globs in the command? They might eventually be passing individual files, and there might be a bug in that method.

If you want I have 2 ideas of things you can try:`

1. Escape the globs in the command, e.g.: `./node_modules/.bin/simple-scaffold text-field -t scaffolds/new-package/\*\*/\* -o packages`
2. If that doesn't work, try using the JS interface to run the Scaffold, I wonder if it'll have any effect on the behavior. Something like:
  ```typescript
  import Scaffold from 'simple-scaffold'

  const name = process.args[1] // or just use "text-field" or whatever name you fancy

  new Scaffold({
    name,
    templates: [path.join(__dirname, "scaffolds", "new-package", "**", "*")],
    output: path.join(__dirname, "packages"),
  }).run()
  ```

**Comment by chenasraf** [comment]
Hey @shaneajeffery, any update? Did one of the solutions help you?
