### ISSUE TITLE
Using locals in command line

### ISSUE THREAD

**Issue by HugoHeneault** [chenasraf/simple-scaffold#20]
Hi there, 

I'm running
```
simple-scaffold --templates 'scaffolds/view/**/*' --output lib/views/ --create-sub-folder --locals {"packagename":"some-app"} OfflineZonesView 
```

But it's not replacing `{{packagename}}` correctly. 

I also tried with 
```
simple-scaffold --templates 'scaffolds/view/**/*' --output lib/views/ --create-sub-folder --locals '{"packagename":"some-app"}' OfflineZonesView 
```

The Readme states we should use it like this:

```
--locals myProp=\"propname\",myVal=123
```

But it doesn't match with whats stated earlier: 

> ```-l, --locals JSON string          A JSON string for the template to use in parsing.  ```

So how could I get my `packagename` replaced? Thanks alot 🙏

**Comment by HugoHeneault** [comment]
Btw, thanks for the 1.0 update, it's working great!

**Comment by chenasraf** [comment]
Hi @HugoHeneault, sorry for the late response!

The 1.0.0 version is pre-release, I'm sorry if there are still issued with it. 

The JSON version of the doc should be the correct one for 1.0.0, but if it still causes issues for you I will have to look into it, there might be problems with that flag.

Also there might be an issue with parsing for the `--create-sub-folder` flag, can you add `true` after it and try with that?

Like so:

```
simple-scaffold --templates 'scaffolds/view/**/*' --output lib/views/ --create-sub-folder --locals '{"packagename":"some-app"}' OfflineZonesView 
```

**Comment by chenasraf** [comment]
Version 1.0.0 is fully released, if you are still having issues please let me know. Also please check [MIGRATION.md](https://github.com/chenasraf/simple-scaffold/blob/master/README.md) for more information on how to upgrade. Re-open the issue or open a new one if you still have problems. Thank you!
