### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by Narretz** [chenasraf/simple-scaffold#25]
Due to path handling that assume `/` is the directory separator, this project doesn't work on Windows.

There's also a problem with handlebars: https://github.com/jknack/handlebars.java/issues/730

Until Windows support is available or if you don't want to support Windows, please add a note to the readme to save others some time.

I actually tried to adapt the code, but ran into some weird errors. If you are interested, I can open a PR.

**Comment by chenasraf** [comment]
Thanks for the report @Narretz, I will try to fix it as soon as possible.

Do you have any console errors when you try? Can you paste them here for reference? Might help me test the fix properly.

From what I remember paths should be OS dependent as I don't chain them manually, I always use `path.join`, but looks like there might be a place I missed. Time to boot up the old VM :)

**Comment by chenasraf** [comment]
Fix is merged, I tested it myself but I am not perfect so if you have any other issues please let me know,

**Comment by Narretz** [comment]
Hi, thanks for the quick response. I ran the tests on my Windows machine, everything looks good. Will test with a real app next week.

**Comment by o68x** [comment]
Hi, I tried your package, and it works well on WSL, but not Windows, where it tries to output the files to a temp directory

```
Writing to C:\Users\Olivier\AppData\Local\Temp\scaffold-config-1727354398122-vradek17ah\node\duplicacy\duplicacy.mjs
File C:\Users\Olivier\AppData\Local\Temp\scaffold-config-1727354398122-vradek17ah\node\duplicacy\duplicacy.mjs already exists, skipping
```
I am using a config file from a github repo.

**Comment by chenasraf** [comment]
That comment seems to indicate you're trying to write over a file that already exists, did you want to add `-w` flag, or maybe the wrong dir?

If the file doesn't actually exist and this is not a false positive, I would appreciate if you can run it again with `-l debug` and paste the logs so I can get a better understanding of what happens

**Comment by o68x** [comment]
Thanks for your answer! Yes, it writes to the wrong dir. I expect it to write to my working dir, but it tries to write to a temp dir in AppData, here `AppData\Local\Temp\scaffold-config-1727354398122-vradek17ah\`.

I will run it with `debug` on later and send you the log.

**Comment by chenasraf** [comment]
I see, I'll do some investigation on my own but yes a log would be much appreciated :) you can open a new issue to make this easier to track.
