### ISSUE TITLE
Creating folder structures

### ISSUE THREAD

**Issue by juhamust** [chenasraf/simple-scaffold#27]
simple-scaffold works nicely when all files are generated into a defined output folder. But could it also allow to create folder structures and files in them, too?

At first, I was expecting the following to adhere to the folder structure, but currently, `simple-scaffold` does output all the files into a defined output folder - unless I'm mistaken something? 🤔

```bash
# This outputs files directly to foo/ (even from the sub folders)
npx simple-scaffold \
  --output foo \
  --templates templates/README.md \
  --templates templates/sub/folder/file1.txt \
  --templates templates/even/deeper/sub/folder/file2.txt
  --name foo
```

One option is to run simple-scaffold to _every_ output folder, but it feels a bit clunky. Agreed?

**Comment by juhamust** [comment]
Hmm. Apparently, there is some kind of folder-creation logic when using template wildcards like `--template template/**` but it is a bit indeterministic 🤔  Perhaps some kind of optional mapping syntax like `--templates templates/sub/folder/file1.txt:sub/folder/file1.txt` could be supported (files generated relative to output folder)?

**Comment by juhamust** [comment]
I stand corrected: Following does exactly what I wanted - just needed to have everything under templates folder, so root folder is determined correctly 👍 

```
npx simple-scaffold \
  --output foo \
  --templates templates/**/* \
  --name foo \
```

This ticket can be closed if need to be.

**Comment by chenasraf** [comment]
Hi @juhamust sorry about the delay - yes, it should maintain the existing folder structure. If you omit `**/*` and use a folder as the template, it should work the same. 

Before, in your first example, you just collected files from several separate locations, and put them in the output. If you include an entire directory as at least one of the templates, it takes that structure and outputs it as it is (or at least it should, if there aren't any bugs).

I will close this but if you find any discrepancies with how it should work and how it actually behaves, please let me know and I will take care of it.

Thanks for the feedback!
