### ISSUE TITLE
"filename" is receiving the entire path instead

### ISSUE THREAD

**Issue by alexandernst** [chenasraf/simple-scaffold#3]
The "filename" parameter of the `output` function receives the entire path of the file, instead of only the file name.

**Comment by chenasraf** [comment]
Thanks for the report. I'll make sure it passes both in the next version. Hopefully before or during this weekend. :)

**Comment by chenasraf** [comment]
New version uploaded to NPM, num is 0.7.1. Please let me know if this can be closed properly :)
