### ISSUE TITLE
Any Thoughts on Adding a Pre Write Block?

### ISSUE THREAD

**Issue by jimjeffers** [chenasraf/simple-scaffold#30]
This library is saving me a lot of time in projects. I've noticed I'll run into some finicky issues with whitespace that could easily be resolved if we could pass a block to the `Scaffold()` function. For example I would like to have prettier run on any new file generated by the command:

```ts
import Scaffold from "simple-scaffold";
import prettier from "prettier"

Scaffold({
      ...options,
      // This could be a new param
      beforeWrite: (content: string) => prettier(content)
    })
```

OR if the Scaffold function simply returns an array of paths to the newly generated files we could just continue to process the files in our pipeline has need be. 

```ts
import Scaffold from "simple-scaffold";
import prettier from "prettier"

const outputs = await Scaffold({
      ...options,
      // This could be a new param
      beforeWrite: (content: string) => prettier(content)
    })

await Promise.all(outputs.map(async (path) => {
  // process file with prettier or maybe even call prettier via pipe from the CLI.
})
```

Any thoughts on what might be a good solution? Or is this already possible as is I'm just missing something in the existing API?

**Comment by chenasraf** [comment]
Hey @jimjeffers, I'm glad the package is useful for you!

This is actually a really good idea, I see no reason this shouldn't be possible to implement rather quickly.

In fact I think both solutions are possible, though I wonder how the second solution would work and both might be implementable together  - since the package returns a void Promise, it might as well return some object with details -- I would want to implement this for CLI as well, so maybe write another file with information when passing a flag, or adding/replacing the output. What do you think a good CLI implementation would be for that?

Either way, I will definitely implement a pre-process function like you suggested. Hopefully I will have time this week.

Also sorry about the late reply, I was traveling for a few days :)

Thanks again for the suggestion - a great idea. I will mention you when it is implemented so you don't miss out on it.

If you have any other ideas feel free to let me know.

**Comment by jimjeffers** [comment]
@chenasraf this is exactly what I needed! It works perfectly for my use case with one exception. I can transform the file with prettier just fine, but I could not resolve the configuration file asynchronously. In my case I could get around this by resolving the configuration earlier in my routine. But that may not always be the case for everyone. It might be best if the `beforeWrite` block could also return the output as a promise for these scenarios.

**Comment by chenasraf** [comment]
Good idea, I will make it a promise. Expect it later today.

**Comment by chenasraf** [comment]
@jimjeffers try out `v1.1.0-alpha.3` :)

**Comment by jimjeffers** [comment]
@chenasraf Thanks!

I get the following error when I attempt to build my package after installing:
`v1.1.0-alpha.2`
`v1.1.0-alpha.3`
`v1.1.0-alpha.4`

```
node_modules/simple-scaffold/types.d.ts:13:30 - error TS2503: Cannot find namespace 'Handlebars'.

13 export declare type Helper = Handlebars.HelperDelegate;
```

**Comment by chenasraf** [comment]
Very odd, I will try to make it work. Hold on.

**Comment by jimjeffers** [comment]
Odd it is happening on `v1.1.0-alpha.1` too I just didn't notice because it only happens when I attempt to build/package the project. Installing handlebars as a dep on my project didn't resolve typescript's complaint.

**Comment by chenasraf** [comment]
@jimjeffers please try `1.1.0-alpha.6`, I made the type explicitly imported, should work better.

**Comment by jimjeffers** [comment]
@chenasraf works like a charm! The promise that is! The package builds without the handlebars complaint too.

**Comment by chenasraf** [comment]
@jimjeffers Awesome! It's a really useful feature, thank you for the suggestion. I was ignoring the bad formatting myself when generating files, knowing they would be formatted eventually by a commit hook. But this makes it much better and actually solves the problem ;)

If there are no further problems I will close this issue, and if after a few days there are no bounce backs I will release 1.1.0 as a full release.

Thanks for the help with testing & debugging, and for the idea :)

**Comment by jimjeffers** [comment]
Of course. Thanks for the quick library update! This rocks. I was doing the same thing but it's nice just to have that extra step already automated. I've only done my limited test with prettier but it looks good to me.

**Comment by chenasraf** [comment]
Gonna use it myself :) I'll close this issue, but feel free to open more or even make PRs if you see room for improvement.
