### ISSUE TITLE
[BUG] Migration 1.x to 2.0

### ISSUE THREAD

**Issue by clabnet** [chenasraf/simple-scaffold#82]
Please describe the changes to this command line (v1 was running) when using the new ver 2.x

#### How To Reproduce

   ```shell
   npx simple-scaffold@latest -c https://github.com/xxxxxxxxxxx.git#scaffold.config.js:pominimfe --name test --output test-fe
   ```

Error : 
```
Error: Cannot find module 'D:\temp\https:\github.com\xxxxxxxxxxxxxxx.git#scaffold.config.js'
```

**Comment by chenasraf** [comment]
The URL syntax has been deprecated - see [Migration](https://chenasraf.github.io/simple-scaffold/docs/usage/migration)

You can just use this format for your command:

```sh
npx simple-scaffold@latest -g clabnet/scaffolds -c scaffold.config.js -k pominimfe  -o test-fe test
```

**Comment by chenasraf** [comment]
That said I am fixing a bug which deleted the tmp directory too early and fails on some git templates, look out for an updated version

**Comment by chenasraf** [comment]
v2.0.1 released [NPM](https://npmjs.com/package/simple-scaffold)

**Comment by clabnet** [comment]
Don't work 2.0.1 version, but it work with v.1.9.0, using the same repository as base.
```
npx simple-scaffold@1.9.0 -c https://github.com/clabnet/scaffolds.git#scaffold.config.js:pominimfe --name test --output test-fe
```
is ok

```
npx simple-scaffold@latest -g clabnet/scaffolds -c scaffold.config.js -k pominimfe  -o test-fe test
```

```
D:\temp>npx simple-scaffold@latest -g clabnet/scaffolds -c scaffold.config.js -k pominimfe  -o test-fe2 test
Loading config from GitHub clabnet/scaffolds
Loading config from scaffold.config.js with key pominimfe
Loading config from remote https://github.com/clabnet/scaffolds.git, file scaffold.config.js
Cloning git repo https://github.com/clabnet/scaffolds.git
Loading config from git repo: https://github.com/clabnet/scaffolds.git
Loaded config from git
Data: {
 "name": "test"
}
Writing to D:\temp\test-fe2\typedoc.json
Done.
Error: ENOENT: no such file or directory, stat 'C:\Users\CLAUDI~1.BAR\AppData\Local\Temp\scaffold-config-1706906485239\templates\pomini-mfe\tsconfig.typedoc.json' {
 "errno": -4058,
 "code": "ENOENT",
 "syscall": "stat",
 "path": "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706906485239\\templates\\pomini-mfe\\tsconfig.typedoc.json"
} Error: ENOENT: no such file or directory, stat 'C:\Users\CLAUDI~1.BAR\AppData\Local\Temp\scaffold-config-1706906485239\templates\pomini-mfe\tsconfig.typedoc.json'
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, stat 'C:\Users\CLAUDI~1.BAR\AppData\Local\Temp\scaffold-config-1706906485239\templates\pomini-mfe\tsconfig.typedoc.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706906485239\\templates\\pomini-mfe\\tsconfig.typedoc.json'
}
```

**Comment by clabnet** [comment]
I sent you a private email via https://casraf.dev/contact. 
Thank for your collaboration.

**Comment by chenasraf** [comment]
I seem to have an error on that form (ironic, I know). Can you email contact@casraf.dev?

And from the logs I see a missing line, it's possible that `npx` didn't actually update the package version?
Try `-h` and see the version number at the end. The output should include the line:

```
Resolving config file: /../github.js
```

**Comment by chenasraf** [comment]
Did you manage to verify you were running v2.0.1?

I was having trouble with `npx` before, it wouldn't always update to the actual latest version.

I am pretty sure you are still on `v2.0.0` because it is missing a debug line I added on the newer version, and I don't see it in your log output.

When you have the time, please let me know if it works or not, so we can resolve any issues left :)

**Comment by clabnet** [comment]
This is the entire response command. 
Same issue :o(
```
npx simple-scaffold@2.0.1 -g xxxxx/scaffolds -c scaffold.config.js -k pominimfe  -o test-fe test  
Need to install the following packages:
simple-scaffold@2.0.1
Ok to proceed? (y) y
Loading config from GitHub xxxxx/scaffolds
Loading config from scaffold.config.js with key pominimfe
Loading config from remote https://github.com/xxxxx/scaffolds.git, file scaffold.config.js
Cloning git repo https://github.com/xxxxx/scaffolds.git
Loading config from git repo: https://github.com/xxxxx/scaffolds.git
Loaded config from git
Data: {
 "name": "test"
}
Writing to D:\_POMINI\src\scaffolds\test-fe\typedoc.json
Done.
Error: ENOENT: no such file or directory, stat 'C:\Users\CLAUDI~1.BAR\AppData\Local\Temp\scaffold-config-1706959459264\templates\pomini-mfe\tsconfig.typedoc.json' {
 "errno": -4058,
 "code": "ENOENT",
 "syscall": "stat",
 "path": "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706959459264\\templates\\pomini-mfe\\tsconfig.typedoc.json"
} Error: ENOENT: no such file or directory, stat 'C:\Users\CLAUDI~1.BAR\AppData\Local\Temp\scaffold-config-1706959459264\templates\pomini-mfe\tsconfig.typedoc.json'
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, stat 'C:\Users\CLAUDI~1.BAR\AppData\Local\Temp\scaffold-config-1706959459264\templates\pomini-mfe\tsconfig.typedoc.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706959459264\\templates\\pomini-mfe\\tsconfig.typedoc.json'
}

Node.js v20.7.0
```

**Comment by clabnet** [comment]
Same issue.

- Cleaned npm cache `npm cache clean` 
- `npm list -g`
```
npm list -g             
C:\Program Files\nodejs -> .\
├── corepack@0.19.0
└── npm@10.1.0
```
- `npx simple-scaffold@2.0.1 -g xxxxxxxxxxx/scaffolds -c scaffold.config.js -k pominimfe  -o test-fe test`
- `npm list`
```
npm list                                                                                          
D:\_POMINI\src\scaffolds
└── (empty)
```
- simple-scaffold --help 
```
Version:  2.0.1
```

Error : 
```
npx simple-scaffold@2.0.1 -g xxxxx/scaffolds -c scaffold.config.js -k pominimfe  -o test-fe test
Loading config from GitHub xxxxx/scaffolds
Loading config from scaffold.config.js with key pominimfe
Loading config from remote https://github.com/xxxxx/scaffolds.git, file scaffold.config.js
Cloning git repo https://github.com/xxxxx/scaffolds.git
Loading config from git repo: https://github.com/xxxxx/scaffolds.git
Loaded config from git
Data: {
 "name": "test"
}
Writing to D:\_POMINI\src\scaffolds\test-fe\typedoc.json
File D:\_POMINI\src\scaffolds\test-fe\typedoc.json already exists, skipping
Writing to D:\_POMINI\src\scaffolds\test-fe\tsconfig.typedoc.json
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open 'C:\Users\CLAUDI~1.BAR\AppData\Local\Temp\scaffold-config-1706960878954\templates\pomini-mfe\tsconfig.typedoc.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706960878954\\templates\\pomini-mfe\\tsconfig.typedoc.json'
}

Node.js v20.7.0
```

**Comment by clabnet** [comment]
Could you try my repo xxxxxxxx

**Comment by chenasraf** [comment]
Can you show the output with `-l debug`? Would print much more info

**Comment by clabnet** [comment]
D:\Weblabs\nginx>npx simple-scaffold@2.0.1 -l -g xxxxxxxxxx/scaffolds -c scaffold.config.js -k pominimfe  -o test-fe test
Loading config from scaffold.config.js with key pominimfe
Loading config from file scaffold.config.js
node:internal/modules/cjs/loader:1048
  const err = new Error(message);
              ^

Error: Cannot find module 'D:\Weblabs\nginx\scaffold.config.js'
Require stack:
- C:\Users\claudio.barca\AppData\Local\npm-cache\_npx\53007d0c62929878\node_modules\simple-scaffold\config.js
- C:\Users\claudio.barca\AppData\Local\npm-cache\_npx\53007d0c62929878\node_modules\simple-scaffold\file.js
- C:\Users\claudio.barca\AppData\Local\npm-cache\_npx\53007d0c62929878\node_modules\simple-scaffold\scaffold.js
- C:\Users\claudio.barca\AppData\Local\npm-cache\_npx\53007d0c62929878\node_modules\simple-scaffold\cmd.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at C:\Users\claudio.barca\AppData\Local\npm-cache\_npx\53007d0c62929878\node_modules\simple-scaffold\config.js:116:100 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\claudio.barca\\AppData\\Local\\npm-cache\\_npx\\53007d0c62929878\\node_modules\\simple-scaffold\\config.js',
    'C:\\Users\\claudio.barca\\AppData\\Local\\npm-cache\\_npx\\53007d0c62929878\\node_modules\\simple-scaffold\\file.js',
    'C:\\Users\\claudio.barca\\AppData\\Local\\npm-cache\\_npx\\53007d0c62929878\\node_modules\\simple-scaffold\\scaffold.js',
    'C:\\Users\\claudio.barca\\AppData\\Local\\npm-cache\\_npx\\53007d0c62929878\\node_modules\\simple-scaffold\\cmd.js'
  ]
}

Node.js v20.7.0

**Comment by chenasraf** [comment]
You seemed to have put `-l` without the `debug` part, so it messed up some of the arguments

**Comment by clabnet** [comment]
D:\_POMINI\src\scaffolds>npx simple-scaffold@2.0.1 -g xxxxx/scaffolds -c scaffold.config.js -k pominimfe  -o test-fe test -l debug
Loading config from GitHub xxxxx/scaffolds
Loading config from scaffold.config.js with key pominimfe
Loading config from remote https://github.com/xxxxx/scaffolds.git, file scaffold.config.js
Cloning git repo https://github.com/xxxxx/scaffolds.git
Cloning git repo to C:\Users\CLAUDI~1.BAR\AppData\Local\Temp\scaffold-config-1706987433542
Loading config from git repo: https://github.com/xxxxx/scaffolds.git
Resolving config file: C:\Users\CLAUDI~1.BAR\AppData\Local\Temp\scaffold-config-1706987433542\scaffold.config.js
Loaded config from git
Raw config: {
 "pominimfe": {
  "templates": [
   "templates/pomini-mfe"
  ]
 }
}
Registering helper: camelCase
Registering helper: snakeCase
Registering helper: startCase
Registering helper: kebabCase
Registering helper: hyphenCase
Registering helper: pascalCase
Registering helper: lowerCase
Registering helper: upperCase
Registering helper: now
Registering helper: date
Full config: {
 "name": "test",
 "templates": [
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe"
 ],
 "output": "test-fe",
 "subdir": false,
 "data": {
  "name": "test"
 },
 "overwrite": false,
 "helpers": [],
 "logLevel": "debug",
 "dryRun": false
}
Data: {
 "name": "test"
}
before isDir isGlob: false C:\Users\CLAUDI~1.BAR\AppData\Local\Temp\scaffold-config-1706987433542\templates\pomini-mfe
after {
 "isDirOrGlob": true,
 "_shouldAddGlob": true
}
Getting file list for C:/Users/CLAUDI~1.BAR/AppData/Local/Temp/scaffold-config-1706987433542/templates/pomini-mfe/**/*
Iterating files {
 "files": [
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\typedoc.json",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\tsconfig.typedoc.json",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\README.md",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\pnpm-workspace.yaml",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\package.json",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\nginx.conf",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\git-init.cmd",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\Dockerfile",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\docker-compose.yml",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\.syncpackrc.js",  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\.prettierrc.js",  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\.prettierignore",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\.npmrc",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\.gitmodules",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\.gitignore",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\.gitattributes",  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\.eslintrc.cjs",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\.eslintignore",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\.editorconfig",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\.dockerignore",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\packages\\.gitkeep",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\devops\\compose.yml",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\devops\\ci.yml",  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\devops\\cd.yml",  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\vitest.config.ts",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\vite.config.ts",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\uno.config.ts",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\tsconfig.json",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\package.json",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\index.html",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\.gitignore",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\.env",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\.vscode\\settings.json",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\.vscode\\launch.json",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\.vscode\\extensions.json",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\src\\vite-env.d.ts",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\src\\main.ts",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\src\\env.ts",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\src\\App.vue",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\public\\loading-icon.svg",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\public\\horizon-web.json",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\public\\horizon-web-local.json",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\public\\favicon.ico",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\src\\views\\HomePage.vue",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\src\\styles\\variables.scss",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\src\\styles\\index.ts",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\src\\router\\index.ts",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\src\\layouts\\SinglePageLayout.vue",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\src\\layouts\\BlankLayout.vue",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\src\\enums\\common.ts",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\src\\core\\constants.ts",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\src\\composables\\useAssets.ts",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\src\\api\\apiClient.ts",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\public\\img\\Pomini_Gemini.png",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\public\\img\\microfrontend-fast-smart.jpg",
  "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\app\\public\\img\\loading-icon.svg"
 ],
 "template": "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\**\\*"
}
{
 "originalTemplate": "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe",
 "relativePath": "",
 "parsedTemplate": "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\**\\*",
 "inputFilePath": "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\typedoc.json",
 "nonGlobTemplate": "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe",
 "basePath": "",
 "isDirOrGlob": true,
 "isGlob": false
}

Parsing C:\Users\CLAUDI~1.BAR\AppData\Local\Temp\scaffold-config-1706987433542\templates\pomini-mfe\typedoc.json
Base path:
Full input path: C:\Users\CLAUDI~1.BAR\AppData\Local\Temp\scaffold-config-1706987433542\templates\pomini-mfe\typedoc.json
Output Path Opt: test-fe
Full output dir: D:\_POMINI\src\scaffolds\test-fe
Full output path: D:\_POMINI\src\scaffolds\test-fe\typedoc.json

Writing to D:\_POMINI\src\scaffolds\test-fe\typedoc.json
File D:\_POMINI\src\scaffolds\test-fe\typedoc.json already exists, skipping
{
 "originalTemplate": "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe",
 "relativePath": "",
 "parsedTemplate": "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\**\\*",
 "inputFilePath": "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\tsconfig.typedoc.json",
 "nonGlobTemplate": "C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe",
 "basePath": "",
 "isDirOrGlob": true,
 "isGlob": false
}

Parsing C:\Users\CLAUDI~1.BAR\AppData\Local\Temp\scaffold-config-1706987433542\templates\pomini-mfe\tsconfig.typedoc.json
Base path:
Full input path: C:\Users\CLAUDI~1.BAR\AppData\Local\Temp\scaffold-config-1706987433542\templates\pomini-mfe\tsconfig.typedoc.json
Output Path Opt: test-fe
Full output dir: D:\_POMINI\src\scaffolds\test-fe
Full output path: D:\_POMINI\src\scaffolds\test-fe\tsconfig.typedoc.json

Writing to D:\_POMINI\src\scaffolds\test-fe\tsconfig.typedoc.json
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open 'C:\Users\CLAUDI~1.BAR\AppData\Local\Temp\scaffold-config-1706987433542\templates\pomini-mfe\tsconfig.typedoc.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\CLAUDI~1.BAR\\AppData\\Local\\Temp\\scaffold-config-1706987433542\\templates\\pomini-mfe\\tsconfig.typedoc.json'
}

Node.js v20.7.0

D:\_POMINI\src\scaffolds>

**Comment by chenasraf** [comment]
@clabnet I think I may have found the issue, can you try `v2.0.2-pre.1`? If it works I will make it a full release.

**Comment by clabnet** [comment]
I can confirm the version v2.0.2-pre.1 has solved the issue. Good job, thank's @chenasraf

**Comment by chenasraf** [comment]
Thanks for the help debugging and sorry for the trouble! I will release it to master
