### ISSUE TITLE
[BUG] Stray space in "homepage", pacakge.json

### ISSUE THREAD

**Issue by hildjj** [chenasraf/simple-scaffold#96]
#### Describe the bug

Inside package.json, the "homepage" value has an extra space in it:

https://github.com/chenasraf/simple-scaffold/blob/ff142d7532bc18b9005e0d2a92966f917a0c8971/package.json#L5C4-L5C13

#### How To Reproduce

1. `npm home simple-scaffold`

    npm error Invalid URL: https:%20//chenasraf.github.io/simple-scaffold

#### Expected behavior\*\*

Browser window opens pointing at https://chenasraf.github.io/simple-scaffold

#### Desktop (please complete the following information):

- OS: macOS
- OS Version: 14.8.1
- Node.js: v22.7.0
- Simple Scaffold Version 2.2.1

**Comment by chenasraf** [comment]
Thanks for the report! I will fix it asap

Just out of curiosity, is there any sort of impact for you other than the warning?

**Comment by hildjj** [comment]
It wasn't just a warning, the URL didn't work, making me think the project was dead.  The third time this happened to me and I actually *looked* at the URL instead of making assumptions, I figured I'd file a bug. :)

Thanks for the quick fix!

**Comment by chenasraf** [comment]
Dunno how it got in there :P thanks again for the report, if you have any more ideas/feedback let me know :)
