### ISSUE TITLE
Filtering the files using config is not working

### ISSUE THREAD

**Issue by sidduspec** [chenasraf/simple-scaffold#98]
As my title says, I am expecting a way to filter out files which are not needed to be included in the scaffolding from my template.
I am not sure if this feature is directly available as I imagine or there there must be a different way to do the same. 

![Image 12-09-24 at 6 28 PM](https://github.com/user-attachments/assets/484a7ab4-0e07-4154-8aba-d5fcabe6cc58)

Output of this will scaffold the entire directory as I need but I need to exclude the files which I don't need be.

Hope I am able to explain my issue.

**Comment by chenasraf** [comment]
Hi @qualitycoder :)

I'm not sure where the `filter`, `overwrite` and `transform` came from;

But here is what you can do:

1. For transforming files, are you only trying to modify the ouput path? In that case, `output` can take a function which will be applied on each file, and overwrite the output path for it. You can see the relevant docs [here](https://chenasraf.github.io/simple-scaffold/docs/api/interfaces/ScaffoldConfig#output).

   ```js
   return Scaffold({
     output: (file) => {
       // file is a string path
       if (file.startsWith(path.join(__dirname, './specbee-cypress/cypress'))) {
         return file.replace(
           path.join(__dirname, './specbee-cypress/cypress'),
           path.join(__dirname, '../..'),
         )
       }
       return path.join(__dirname, '../..', file)
     },
   })
   ```

   You might want to play around with the path outputs, I'm not sure exactly how your file structure looks.

1. As for filtering out files/folders, that sounds like a really good feature suggestion; but until that is implemented, it's only possible if you specify the folders you want to add, like this:

   ```js
   return Scaffold({
     templates: [
       // add children of . instead of . directly:
       './folder1',
       './folder2',
       // ...
     ],
   })
   ```

   I was sure negative globs would be supported, but it's either a bug or I misunderstood the glob library, I will do my best to fix that or see what I can do there.

Do these work for you? Let me know if you need further help

I will update here when I get the chance to add better filtering.

**Comment by sidduspec** [comment]
hi @chenasraf , Your workaround for filter is working fine with your approach and takes exactly the same files/folder I need but, output is not as expected. I m just not trying to modify the path instead, I want to copy the files/folder with the original structure into my root. 

![40A3577C-D5F0-40AA-B22D-EC4BF7524CC8_1_201_a](https://github.com/user-attachments/assets/b2281101-fff0-4b54-aab8-2f37de10089a)

In the above screenshot, I get the output inside a folder with absolute path. I tried using path to resolve these conflicts but no success.

My original folder structure
<img width="711" alt="image" src="https://github.com/user-attachments/assets/9e9184d0-95fc-474e-9fcf-3d5a7e87c89d">

I want exactly the same structure upon scaffolding into the root the the project where I install.

**Comment by chenasraf** [comment]
I will work on improving the glob patterns so exclusions can be added. Maybe even an `ignore` list.

Hopefully I will have time either this week or next week to push an update.

As for fixing the paths right now, maybe try outputting a relative path instead of an absolute path in `output`? It appears I have a bug here where it unnecessarily strips the leading `/` so it treats it as relative.

Try to make `output` return paths that are relative to the directory you want to output in

Once I figure out some better path resolution strategies, it's possible this can be removed

**Comment by chenasraf** [comment]
@sidduspec Just released v2.3.0, if you want to exclude any glob patterns from templates, just prepend a glob pattern or file with `!`, like so:

```ts
return Scaffold({
  templates: [
    '.',
    '!bitbucket-pipeline/',
    '!scaffold.js',
    '!README.md',
    '!node_modules/',
    '!package-lock.json',
  ],
})
```

Let me know if that works for you or not

**Comment by sidduspec** [comment]
@chenasraf , Your solution to exclude files seems working fine. But I am not able to output the exact structure as I want. Please find my file structure attached.

I am checking for folder or file and doing the scaffolding accordingly. Still I get the below error
<img width="1109" alt="image" src="https://github.com/user-attachments/assets/bf921fa8-490b-411a-9641-04f06af60e9e">

My folder Structure and config file:
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/60b46551-edd1-45f1-8043-a5d4ec5987f5">

**Comment by chenasraf** [comment]
No need to resolve the file paths in the templates directory, that seems to be causing issues.
Just supply a relative path to the template, can be `.` for example. Then add the excludes later.

```ts
```

**Comment by sidduspec** [comment]
@chenasraf , Thanks for your help. Issue resolved when I stopped resolving the path. We can happily close this.

**Comment by chenasraf** [comment]
Glad it's working :)
